// content/trace.mjs —— 一条录好的运行（离线静态数据，回放不发任何模型请求）。
// 每个事件绑定 agent-loop.ts 里「产生它」的那一行，逐帧回放时高亮对应代码。
export const trace = {
  scenario: "用户让 agent 读 config.json 并把 version 改成 2.0.0",
  code: [
    'async function runTurn(log, model, tools, userText) {',
    '  const turnId = crypto.randomUUID()',
    '  log.append({ type: "turn/start", turnId })',
    '  log.append({ type: "user/message", text: userText })',
    '  while (true) {',
    '    const history = deriveMessages(log.all())',
    '    const { text, toolCalls } =',
    '      await streamAssistant(model, history, log)  // 逐字 append assistant/chunk',
    '    log.append({ type: "assistant/message", text, toolCalls })',
    '    if (toolCalls.length === 0) break',
    '    for (const tc of toolCalls) {',
    '      log.append({ type: "tool/call", id: tc.id, name: tc.name, args: tc.args })',
    '      const result = await tools[tc.name](tc.args)',
    '      log.append({ type: "tool/result", id: tc.id, content: result })',
    '    }',
    '  }',
    '  log.append({ type: "turn/end", turnId })',
    '}',
  ],
  events: [
    { type: "turn/start",        line: 3,  note: "开一轮。turn 是耐久事件，记录「这次运行开始了」。", data: { turnId: "t_01" } },
    { type: "user/message",      line: 4,  note: "用户输入落日志，它会进入模型历史。", data: { text: "读 config.json，把 version 改成 2.0.0" } },
    { type: "assistant/chunk",   line: 8,  note: "流式增量，只为回放/UI 保真，不进模型历史。", data: { delta: "好的，我先" } },
    { type: "assistant/chunk",   line: 8,  note: "又一个增量。回放时可逐字重演。", data: { delta: "读一下文件…" } },
    { type: "assistant/message", line: 9,  note: "模型完整回复 + 要调的工具。进入模型历史。", data: { text: "好的，我先读一下文件…", toolCalls: [{ id: "c1", name: "read_file", args: { path: "config.json" } }] } },
    { type: "tool/call",         line: 12, note: "发起工具调用。这条不进模型历史（历史里体现在 assistant.toolCalls 上）。", data: { id: "c1", name: "read_file", args: { path: "config.json" } } },
    { type: "tool/result",       line: 14, note: "工具结果落日志，作为 role:tool 进入模型历史。", data: { id: "c1", content: '{ "version": "1.4.2" }' } },
    { type: "assistant/message", line: 9,  note: "模型读到内容后，决定调用 edit 改写。", data: { text: "读到 version 是 1.4.2，我来改成 2.0.0。", toolCalls: [{ id: "c2", name: "edit", args: { path: "config.json", old: "1.4.2", new: "2.0.0" } }] } },
    { type: "tool/call",         line: 12, note: "第二次工具调用：精确替换。", data: { id: "c2", name: "edit", args: { path: "config.json", old: "1.4.2", new: "2.0.0" } } },
    { type: "tool/result",       line: 14, note: "改写成功。", data: { id: "c2", content: "edited config.json: 1 replacement" } },
    { type: "assistant/message", line: 9,  note: "没有工具调用了，本轮结束。", data: { text: "已把 version 改成 2.0.0 ✅", toolCalls: [] } },
    { type: "turn/end",          line: 17, note: "一轮结束。整条日志可 replay、可从任意点 fork。", data: { turnId: "t_01" } },
  ],
};
