// scripts/generate-content.mjs
// 构建时同步：从 nano-src/*.ts 的 region 标记提取真实代码切片，与 content/ 的正文合并，
// 产出 app/generated/content.ts。这样「右侧展示的代码」永远等于仓库里的真实源码。
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { meta, steps } from "../content/steps.mjs";
import { trace } from "../content/trace.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// 解析一个源码文件里的 region：//#region <id> ... //#endregion
// 支持嵌套：一行会归入当前所有处于开启状态的 region（用栈维护），
// 这样外层大 region 与内层聚焦切片可以共存，互不破坏。
function parseRegions(file) {
  const text = readFileSync(join(root, "nano-src", file), "utf8");
  const lines = text.split("\n");
  const regions = {};
  const stack = [];
  for (const line of lines) {
    const start = line.match(/^\s*\/\/#region\s+(\S+)/);
    const end = line.match(/^\s*\/\/#endregion/);
    if (start) { const id = start[1]; if (!regions[id]) regions[id] = []; stack.push(id); continue; }
    if (end) { stack.pop(); continue; }
    for (const id of stack) regions[id].push(line);
  }
  // 去掉每个 region 首尾多余空行
  for (const k of Object.keys(regions)) {
    while (regions[k].length && regions[k][0].trim() === "") regions[k].shift();
    while (regions[k].length && regions[k][regions[k].length - 1].trim() === "") regions[k].pop();
    regions[k] = regions[k].join("\n");
  }
  return regions;
}

const cache = {};
function codeFor(file, region) {
  cache[file] = cache[file] || parseRegions(file);
  const code = cache[file][region];
  if (code == null) throw new Error(`region "${region}" not found in nano-src/${file}`);
  return code;
}

// 解析整份源码文件：剥掉 //#region / //#endregion 这类构建标记（它们只是切片脚手架，
// 不是 dsh 真正的逻辑代码），得到一份干净可读的「完整源码」，供右侧「点文件标签看整份文件」使用；
// 同时记录每个 region 在这份干净源码里对应的行号区间（支持被拆成多段的 region → 多个区间），
// 这样浏览整文件时能把「当前 step 对应的那一段」高亮出来。
function parseFullFile(file) {
  const text = readFileSync(join(root, "nano-src", file), "utf8");
  const lines = text.split("\n");
  const out = [];
  const regions = {}; // id -> [{ start, end }]（行号从 1 起）
  const stack = [];
  for (const line of lines) {
    const start = line.match(/^\s*\/\/#region\s+(\S+)/);
    const end = line.match(/^\s*\/\/#endregion/);
    if (start) { stack.push({ id: start[1], start: out.length + 1 }); continue; }
    if (end) {
      const top = stack.pop();
      if (top) (regions[top.id] = regions[top.id] || []).push({ start: top.start, end: out.length });
      continue;
    }
    out.push(line);
  }
  return { code: out.join("\n"), regions };
}

const outSteps = steps.map((s) => ({
  id: s.id,
  file: s.file,
  region: s.region,
  title: s.title,
  prose: s.prose,
  principleProse: s.principleProse ?? null,
  code: codeFor(s.file, s.region),
}));

// 项目涉及的全部源码文件：按 steps 中首次出现的顺序去重，保证「文件列表」既准确又不多不少。
const fileOrder = [];
for (const s of steps) if (!fileOrder.includes(s.file)) fileOrder.push(s.file);
const files = fileOrder.map((name) => {
  const { code, regions } = parseFullFile(name);
  return { name, code, regions };
});

// 命名代码切片：供正文中「原理块」右侧直接引用真实源码的聚焦片段。
const snippets = {
  provide: { file: "kernel.ts", code: codeFor("kernel.ts", "kp") },
  use: { file: "kernel.ts", code: codeFor("kernel.ts", "k3") },
};

const TUTORIAL = { meta, steps: outSteps, trace, snippets, files };

const banner =
  "// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.\n" +
  "// 代码切片来自 nano-src/*.ts（真实源码），正文来自 content/steps.mjs。\n";
const body = `export const TUTORIAL = ${JSON.stringify(TUTORIAL, null, 2)} as const;\n`;

mkdirSync(join(root, "app", "generated"), { recursive: true });
writeFileSync(join(root, "app", "generated", "content.ts"), banner + body, "utf8");
console.log(`[generate-content] wrote app/generated/content.ts · ${outSteps.length} steps, ${trace.events.length} trace events`);
