// scripts/generate-content.mjs
// 构建时同步：从 nano-src/*.ts 的 region 标记提取真实代码切片，与 content/ 的正文合并，
// 产出 app/generated/content.ts。这样「右侧展示的代码」永远等于仓库里的真实源码。
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { meta, steps } from "../content/steps.mjs";
import { trace } from "../content/trace.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// 解析一个源码文件里的 region：//#region <id> ... //#endregion
function parseRegions(file) {
  const text = readFileSync(join(root, "nano-src", file), "utf8");
  const lines = text.split("\n");
  const regions = {};
  let cur = null;
  for (const line of lines) {
    const start = line.match(/^\s*\/\/#region\s+(\S+)/);
    const end = line.match(/^\s*\/\/#endregion/);
    if (start) { cur = start[1]; regions[cur] = []; continue; }
    if (end) { cur = null; continue; }
    if (cur) regions[cur].push(line);
  }
  // 去掉每个 region 首尾多余空行
  for (const k of Object.keys(regions)) {
    while (regions[k].length && regions[k][0].trim() === "") regions[k].shift();
    while (regions[k].length && regions[k][regions[k].length - 1].trim() === "") regions[k].pop();
    regions[k] = regions[k].join("\n");
  }
  return regions;
}

const cache = {};
function codeFor(file, region) {
  cache[file] = cache[file] || parseRegions(file);
  const code = cache[file][region];
  if (code == null) throw new Error(`region "${region}" not found in nano-src/${file}`);
  return code;
}

const outSteps = steps.map((s) => ({
  id: s.id,
  file: s.file,
  title: s.title,
  prose: s.prose,
  code: codeFor(s.file, s.region),
}));

const TUTORIAL = { meta, steps: outSteps, trace };

const banner =
  "// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.\n" +
  "// 代码切片来自 nano-src/*.ts（真实源码），正文来自 content/steps.mjs。\n";
const body = `export const TUTORIAL = ${JSON.stringify(TUTORIAL, null, 2)} as const;\n`;

mkdirSync(join(root, "app", "generated"), { recursive: true });
writeFileSync(join(root, "app", "generated", "content.ts"), banner + body, "utf8");
console.log(`[generate-content] wrote app/generated/content.ts · ${outSteps.length} steps, ${trace.events.length} trace events`);
